# Generated by Django 3.1 on 2020-08-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20200815_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='block_id',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='reserve_price_id',
            new_name='reserve_price',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='user_id',
            new_name='user',
        ),
    ]
